/*
    src/store/user/constants

    User constants for dispatching
*/

export const SET_USER_QUERY = 'SET/USER/QUERY'
export const SET_USER_QUERY_PREV = 'SET/USER/QUERY/PREV'

export const SET_USER_SELECTED = 'SET/USER/SELECTED'

export const SET_USER_EVENTS_NEXT = 'SET/USER/EVENTS/NEXT'
export const SET_USER_EVENTS_PREV = 'SET/USER/EVENTS/PREV'

export const SET_USER_REPOS_PANEL = 'SET/USER/REPOS/PANEL'
export const SET_USER_REPOS_NEXT = 'SET/USER/REPOS/NEXT'
export const SET_USER_REPOS_PREV = 'SET/USER/REPOS/PREV'

export const SET_USER_FOLLOWINGS_PANEL = 'SET/USER/FOLLOWINGS/PANEL'
export const SET_USER_FOLLOWINGS_NEXT = 'SET/USER/FOLLOWINGS/NEXT'
export const SET_USER_FOLLOWINGS_PREV = 'SET/USER/FOLLOWINGS/PREV'

export const SET_USER_FOLLOWERS_PANEL = 'SET/USER/FOLLOWERS/PANEL'
export const SET_USER_FOLLOWERS_NEXT = 'SET/USER/FOLLOWERS/NEXT'
export const SET_USER_FOLLOWERS_PREV = 'SET/USER/FOLLOWERS/PREV'
