/*
    src/store/project/constants

    Project constants for dispatching
*/

export const SET_PROJECT_QUERY = 'SET/PROJECT/QUERY'
export const SET_PROJECT_QUERY_PREV = 'SET/PROJECT/QUERY/PREV'

export const SET_PROJECT_SELECTED = 'SET/PROJECT/SELECTED'
export const SET_PROJECT_CONTENTS = 'SET/PROJECT/CONTENTS'
export const SET_PROJECT_LANGUAGES = 'SET/PROJECT/LANGUAGES'
export const SET_PROJECT_CONTRIBUTORS = 'SET/PROJECT/CONTRIBUTORS'
